import type { Metadata } from "next";
// Imports the type used to define page metadata (title, description, SEO info).

import localFont from "next/font/local";
// Utility for loading custom local fonts efficiently in Next.js.

import "./globals.css";
// Imports global CSS styles applied to the entire application.

import { ThirdwebProvider } from "thirdweb/react";
// Provider that enables blockchain and wallet functionality across the app.

import { Toaster } from "@/components/ui/toaster";
// UI component responsible for showing toast notifications
// (success, error, info messages).

/* ----------------------------------
   Custom font setup
---------------------------------- */

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  // Path to the local Sans-serif font file.

  variable: "--font-geist-sans",
  // CSS variable name used to reference this font in styles.

  weight: "100 900",
  // Allows the full range of font weights (thin → bold).
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  // Path to the local Monospace font file.

  variable: "--font-geist-mono",
  // CSS variable name for the monospace font.

  weight: "100 900",
  // Full weight range for consistent typography.
});

/* ----------------------------------
   Global metadata (SEO)
---------------------------------- */

export const metadata: Metadata = {
  title: "Create Next App",
  // Default page title for the application.

  description: "Generated by create next app",
  // Default meta description for search engines and previews.
};

/* ----------------------------------
   Root layout component
---------------------------------- */

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Root layout wraps every page in the application.
  // Anything placed here appears on ALL pages.

  return (
    <html lang="en">
      {/* Sets the document language for accessibility and SEO */}

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 
          Applies the custom fonts globally using CSS variables.
          "antialiased" improves text rendering quality.
        */}

        <ThirdwebProvider>
          {/* 
            Makes Thirdweb (wallets, blockchain interactions)
            available to all child components.
          */}
          {children}
        </ThirdwebProvider>

        <Toaster />
        {/* 
          Global toast notification system.
          Can be triggered from anywhere in the app.
        */}
      </body>
    </html>
  );
}
